#Remember : docker context use default
services: 
  neo4j:
    build: 
      context: .
      dockerfile: Dockerfile 
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP Port for Neo4j browser
      - "7687:7687"  # Bold port for database connections
    environment: 
      - NEO4J_AUTH=neo4j/password   # Replace 'password' with your desired password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    restart: on-failure
    volumes:
      - ./data2:/data # Store Neo4j data locally     
      - ./import:/var/lib/neo4j/import # Store formatted data locally

